# ChitLaq M1 MVP - Prometheus Configuration
# Comprehensive monitoring for all services

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'chitlaq-production'
    replica: 'prometheus-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules from files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: /metrics

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s
    metrics_path: /metrics

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    metrics_path: /metrics

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 10s
    metrics_path: /metrics

  # Supabase Kong metrics
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    scrape_interval: 15s
    metrics_path: /metrics

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application metrics (when applications are developed)
  - job_name: 'chitlaq-api'
    static_configs:
      - targets: ['api-gateway:3001']
    scrape_interval: 10s
    metrics_path: /metrics
    honor_labels: true

  - job_name: 'chitlaq-auth'
    static_configs:
      - targets: ['auth-service:3002']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'chitlaq-realtime'
    static_configs:
      - targets: ['realtime-service:3003']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'chitlaq-feed'
    static_configs:
      - targets: ['feed-service:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'chitlaq-search'
    static_configs:
      - targets: ['search-service:8081']
    scrape_interval: 10s
    metrics_path: /metrics

  # Health check endpoints
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'postgres:5432'
        - 'redis:6379'
        - 'kong:8000'
        - 'rest:3000'
        - 'auth:9999'
        - 'realtime:4000'
        - 'storage:5000'
    scrape_interval: 30s
    metrics_path: /health
    params:
      format: ['prometheus']

# Storage configuration
storage:
  tsdb:
    path: /prometheus/
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Remote write configuration (for backup/federation)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "your_username"
#       password: "your_password"

# Federation configuration (if multiple Prometheus instances)
# - job_name: 'federate'
#   scrape_interval: 15s
#   honor_labels: true
#   metrics_path: '/federate'
#   params:
#     'match[]':
#       - '{job=~"prometheus|node-exporter|postgres|redis"}'
#   static_configs:
#     - targets:
#       - 'prometheus-2:9090'
