#!/bin/bash

# ChitLaq M1 MVP - Production Deployment Script
# Generated by PROMPT 1.5 - CI/CD Pipeline & Automated Deployment
# Senior DevOps Engineer - 15+ years CI/CD and release management experience

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENVIRONMENT="production"
DEPLOYMENT_ID=""
BLUE_GREEN_MODE=true
SKIP_TESTS=false
FORCE_DEPLOY=false
MAINTENANCE_MODE=false

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Usage function
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Production deployment script for ChitLaq M1 MVP

OPTIONS:
    --deployment-id ID    Deployment ID (required)
    --blue-green          Enable blue-green deployment (default: true)
    --skip-tests          Skip running tests
    --force               Force deployment (skip checks)
    --maintenance         Enable maintenance mode during deployment
    --help                Show this help message

EXAMPLES:
    $0 --deployment-id 20241201-143022
    $0 --deployment-id 20241201-143022 --maintenance
    $0 --deployment-id 20241201-143022 --skip-tests --force

EOF
}

# Parse command line arguments
parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --deployment-id)
                DEPLOYMENT_ID="$2"
                shift 2
                ;;
            --blue-green)
                BLUE_GREEN_MODE=true
                shift
                ;;
            --skip-tests)
                SKIP_TESTS=true
                shift
                ;;
            --force)
                FORCE_DEPLOY=true
                shift
                ;;
            --maintenance)
                MAINTENANCE_MODE=true
                shift
                ;;
            --help)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    # Validate required arguments
    if [[ -z "$DEPLOYMENT_ID" ]]; then
        log_error "Deployment ID is required"
        usage
        exit 1
    fi
}

# Pre-deployment checks
pre_deployment_checks() {
    log_info "Running pre-deployment checks..."

    # Check if deployment directory exists
    if [[ ! -d "$PROJECT_ROOT" ]]; then
        log_error "Project root directory not found: $PROJECT_ROOT"
        exit 1
    fi

    # Check if required files exist
    local required_files=(
        "docker-compose.yml"
        ".env"
        "package.json"
    )

    for file in "${required_files[@]}"; do
        if [[ ! -f "$PROJECT_ROOT/$file" ]]; then
            log_error "Required file not found: $file"
            exit 1
        fi
    done

    # Check Docker availability
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed or not in PATH"
        exit 1
    fi

    if ! command -v docker-compose &> /dev/null; then
        log_error "Docker Compose is not installed or not in PATH"
        exit 1
    fi

    # Check if Docker daemon is running
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running"
        exit 1
    fi

    # Check disk space (minimum 10GB free for production)
    local available_space=$(df "$PROJECT_ROOT" | awk 'NR==2 {print $4}')
    local required_space=10485760 # 10GB in KB
    
    if [[ $available_space -lt $required_space ]]; then
        log_error "Insufficient disk space. Required: 10GB, Available: $((available_space / 1024 / 1024))GB"
        exit 1
    fi

    # Check memory (minimum 8GB available for production)
    local available_memory=$(free -m | awk 'NR==2{printf "%.0f", $7}')
    local required_memory=8192 # 8GB in MB
    
    if [[ $available_memory -lt $required_memory ]]; then
        log_error "Insufficient memory. Required: 8GB, Available: ${available_memory}MB"
        exit 1
    fi

    # Check if production environment is healthy
    if ! curl -f "https://chitlaq.com/health" &> /dev/null; then
        log_warning "Production environment health check failed"
        if ! $FORCE_DEPLOY; then
            log_error "Cannot deploy to unhealthy production environment"
            exit 1
        fi
    fi

    log_success "Pre-deployment checks passed"
}

# Environment setup
setup_environment() {
    log_info "Setting up production environment..."

    # Load environment variables
    if [[ -f "$PROJECT_ROOT/.env" ]]; then
        set -a
        source "$PROJECT_ROOT/.env"
        set +a
        log_info "Environment variables loaded from .env"
    else
        log_error "Environment file not found: .env"
        exit 1
    fi

    # Set deployment-specific environment variables
    export DEPLOYMENT_ID="$DEPLOYMENT_ID"
    export ENVIRONMENT="$ENVIRONMENT"
    export COMPOSE_PROJECT_NAME="chitlaq-production"

    # Create necessary directories
    mkdir -p "$PROJECT_ROOT/logs"
    mkdir -p "$PROJECT_ROOT/backups"
    mkdir -p "$PROJECT_ROOT/data"
    mkdir -p "$PROJECT_ROOT/ssl"

    # Set production-specific configurations
    export NODE_ENV="production"
    export LOG_LEVEL="info"
    export ENABLE_METRICS="true"

    log_success "Production environment setup completed"
}

# Enable maintenance mode
enable_maintenance_mode() {
    if $MAINTENANCE_MODE; then
        log_info "Enabling maintenance mode..."

        # Create maintenance page
        cat > "$PROJECT_ROOT/nginx/maintenance.html" << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>ChitLaq - Maintenance</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        .container { max-width: 600px; margin: 0 auto; }
        h1 { color: #333; }
        p { color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🚧 Maintenance in Progress</h1>
        <p>We're currently updating ChitLaq to bring you new features and improvements.</p>
        <p>We'll be back online shortly. Thank you for your patience!</p>
        <p><small>Expected downtime: 5-10 minutes</small></p>
    </div>
</body>
</html>
EOF

        # Update nginx configuration to show maintenance page
        # This would typically involve updating nginx config and reloading
        log_info "Maintenance mode enabled"
    fi
}

# Disable maintenance mode
disable_maintenance_mode() {
    if $MAINTENANCE_MODE; then
        log_info "Disabling maintenance mode..."

        # Remove maintenance page
        rm -f "$PROJECT_ROOT/nginx/maintenance.html"

        # Restore normal nginx configuration
        # This would typically involve updating nginx config and reloading
        log_info "Maintenance mode disabled"
    fi
}

# Database migration
run_database_migration() {
    log_info "Running production database migration..."

    # Check if database is accessible
    if ! docker-compose -f "$PROJECT_ROOT/docker-compose.yml" exec -T postgres pg_isready -U postgres &> /dev/null; then
        log_error "Database is not accessible"
        exit 1
    fi

    # Create encrypted backup before migration
    log_info "Creating encrypted pre-migration backup..."
    local backup_file="$PROJECT_ROOT/backups/pre-migration-$(date +%Y%m%d-%H%M%S).sql"
    docker-compose -f "$PROJECT_ROOT/docker-compose.yml" exec -T postgres pg_dump -U postgres chitlaq > "$backup_file"
    
    # Encrypt backup
    if command -v gpg &> /dev/null; then
        gpg --symmetric --cipher-algo AES256 --output "$backup_file.gpg" "$backup_file"
        rm "$backup_file"
        log_info "Backup encrypted: $(basename "$backup_file.gpg")"
    fi

    # Run migrations with safety checks
    if [[ -d "$PROJECT_ROOT/migrations" ]]; then
        log_info "Running database migrations with safety checks..."
        for migration in "$PROJECT_ROOT/migrations"/*.sql; do
            if [[ -f "$migration" ]]; then
                log_info "Applying migration: $(basename "$migration")"
                
                # Check if migration is safe for production
                if grep -q "DROP\|DELETE\|TRUNCATE" "$migration"; then
                    log_warning "Migration contains potentially destructive operations: $(basename "$migration")"
                    if ! $FORCE_DEPLOY; then
                        log_error "Destructive migration detected. Use --force to override."
                        exit 1
                    fi
                fi
                
                docker-compose -f "$PROJECT_ROOT/docker-compose.yml" exec -T postgres psql -U postgres -d chitlaq -f "/migrations/$(basename "$migration")"
            fi
        done
    else
        log_warning "No migrations directory found"
    fi

    log_success "Production database migration completed"
}

# Build and pull images
build_images() {
    log_info "Building and pulling production Docker images..."

    # Pull latest images
    log_info "Pulling latest images..."
    docker-compose -f "$PROJECT_ROOT/docker-compose.yml" pull

    # Build custom images with production optimizations
    log_info "Building production-optimized images..."
    docker-compose -f "$PROJECT_ROOT/docker-compose.yml" build --no-cache --parallel

    # Tag images with deployment ID
    log_info "Tagging images with deployment ID: $DEPLOYMENT_ID"
    docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.ID}}" | grep chitlaq | while read -r repo tag id; do
        if [[ "$tag" != "latest" ]]; then
            docker tag "$id" "$repo:$DEPLOYMENT_ID"
        fi
    done

    # Scan images for vulnerabilities
    log_info "Scanning images for vulnerabilities..."
    if command -v trivy &> /dev/null; then
        docker images --format "{{.Repository}}:{{.Tag}}" | grep chitlaq | while read -r image; do
            log_info "Scanning image: $image"
            trivy image --severity HIGH,CRITICAL "$image" || log_warning "Vulnerabilities found in $image"
        done
    fi

    log_success "Production image build and pull completed"
}

# Blue-green deployment
blue_green_deployment() {
    log_info "Starting blue-green production deployment..."

    # Determine current and new environments
    local current_env=""
    local new_env=""

    if docker-compose -f "$PROJECT_ROOT/docker-compose.yml" ps | grep -q "chitlaq-production-blue"; then
        current_env="blue"
        new_env="green"
    else
        current_env="green"
        new_env="blue"
    fi

    log_info "Current environment: $current_env, New environment: $new_env"

    # Start new environment
    log_info "Starting new production environment ($new_env)..."
    export COMPOSE_PROJECT_NAME="chitlaq-production-$new_env"
    docker-compose -f "$PROJECT_ROOT/docker-compose.yml" up -d

    # Wait for new environment to be ready
    log_info "Waiting for new environment to be ready..."
    local max_attempts=60
    local attempt=1

    while [[ $attempt -le $max_attempts ]]; do
        if curl -f "http://localhost:3001/health" &> /dev/null; then
            log_success "New environment is ready"
            break
        fi

        if [[ $attempt -eq $max_attempts ]]; then
            log_error "New environment failed to start within timeout"
            docker-compose -f "$PROJECT_ROOT/docker-compose.yml" logs
            exit 1
        fi

        log_info "Waiting for new environment... (attempt $attempt/$max_attempts)"
        sleep 10
        ((attempt++))
    done

    # Run comprehensive health checks on new environment
    if ! $SKIP_TESTS; then
        log_info "Running comprehensive health checks on new environment..."
        "$PROJECT_ROOT/scripts/health-check.sh" --env=production --comprehensive --timeout=300
    fi

    # Gradual traffic switching
    log_info "Starting gradual traffic switching..."
    
    # Phase 1: Route 10% traffic to new environment
    log_info "Phase 1: Routing 10% traffic to new environment"
    # Update load balancer configuration
    sleep 30

    # Phase 2: Route 50% traffic to new environment
    log_info "Phase 2: Routing 50% traffic to new environment"
    # Update load balancer configuration
    sleep 60

    # Phase 3: Route 100% traffic to new environment
    log_info "Phase 3: Routing 100% traffic to new environment"
    # Update load balancer configuration
    sleep 30

    # Verify traffic switching
    log_info "Verifying traffic switching..."
    local health_check_attempts=0
    local max_health_checks=10

    while [[ $health_check_attempts -lt $max_health_checks ]]; do
        if curl -f "https://chitlaq.com/health" &> /dev/null; then
            log_success "Traffic switching verified"
            break
        fi

        if [[ $health_check_attempts -eq $((max_health_checks - 1)) ]]; then
            log_error "Traffic switching verification failed"
            exit 1
        fi

        log_info "Verifying traffic switching... (attempt $((health_check_attempts + 1))/$max_health_checks)"
        sleep 30
        ((health_check_attempts++))
    done

    # Stop old environment
    log_info "Stopping old environment ($current_env)..."
    export COMPOSE_PROJECT_NAME="chitlaq-production-$current_env"
    docker-compose -f "$PROJECT_ROOT/docker-compose.yml" down

    log_success "Blue-green production deployment completed"
}

# Post-deployment tasks
post_deployment_tasks() {
    log_info "Running post-deployment tasks..."

    # Run comprehensive health checks
    if ! $SKIP_TESTS; then
        log_info "Running comprehensive health checks..."
        "$PROJECT_ROOT/scripts/health-check.sh" --env=production --comprehensive --timeout=300
    fi

    # Warm up caches and critical endpoints
    log_info "Warming up caches and critical endpoints..."
    local endpoints=(
        "https://chitlaq.com/api/health"
        "https://chitlaq.com/api/feed"
        "https://chitlaq.com/api/search?q=test"
        "https://chitlaq.com/api/auth/status"
    )

    for endpoint in "${endpoints[@]}"; do
        curl -f "$endpoint" &> /dev/null || log_warning "Failed to warm up: $endpoint"
    done

    # Update monitoring and alerting
    log_info "Updating monitoring configuration..."
    # Update Prometheus targets
    # Update Grafana dashboards
    # Test alerting rules

    # Update CDN cache
    log_info "Invalidating CDN cache..."
    # This would typically involve calling CDN API to invalidate cache

    # Update search index
    log_info "Updating search index..."
    curl -X POST "https://chitlaq.com/api/search/reindex" &> /dev/null || log_warning "Search reindex failed"

    # Clean up old images (keep last 3 versions)
    log_info "Cleaning up old images..."
    docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.ID}}" | grep chitlaq | tail -n +4 | awk '{print $3}' | xargs -r docker rmi

    # Update deployment status
    log_info "Updating deployment status..."
    # This would typically involve updating a deployment tracking system

    log_success "Post-deployment tasks completed"
}

# Rollback function
rollback() {
    log_warning "Rolling back production deployment..."

    # Stop current services
    docker-compose -f "$PROJECT_ROOT/docker-compose.yml" down

    # Restore from encrypted backup if available
    local latest_backup=$(ls -t "$PROJECT_ROOT/backups"/*.gpg 2>/dev/null | head -n 1)
    if [[ -n "$latest_backup" ]]; then
        log_info "Restoring database from encrypted backup: $(basename "$latest_backup")"
        docker-compose -f "$PROJECT_ROOT/docker-compose.yml" up -d postgres
        sleep 10
        
        # Decrypt and restore backup
        gpg --decrypt "$latest_backup" | docker-compose -f "$PROJECT_ROOT/docker-compose.yml" exec -T postgres psql -U postgres -d chitlaq
    fi

    # Start previous version
    docker-compose -f "$PROJECT_ROOT/docker-compose.yml" up -d

    # Verify rollback
    sleep 30
    if curl -f "https://chitlaq.com/health" &> /dev/null; then
        log_success "Rollback completed and verified"
    else
        log_error "Rollback verification failed"
        exit 1
    fi
}

# Main deployment function
main() {
    log_info "Starting production deployment..."
    log_info "Deployment ID: $DEPLOYMENT_ID"
    log_info "Environment: $ENVIRONMENT"
    log_info "Blue-Green Mode: $BLUE_GREEN_MODE"
    log_info "Skip Tests: $SKIP_TESTS"
    log_info "Force Deploy: $FORCE_DEPLOY"
    log_info "Maintenance Mode: $MAINTENANCE_MODE"

    # Change to project root directory
    cd "$PROJECT_ROOT"

    # Run deployment steps
    if ! $FORCE_DEPLOY; then
        pre_deployment_checks
    fi

    setup_environment
    enable_maintenance_mode
    run_database_migration
    build_images

    if $BLUE_GREEN_MODE; then
        blue_green_deployment
    else
        log_error "Standard deployment not supported for production. Use blue-green deployment."
        exit 1
    fi

    post_deployment_tasks
    disable_maintenance_mode

    log_success "Production deployment completed successfully!"
    log_info "Deployment ID: $DEPLOYMENT_ID"
    log_info "Environment: $ENVIRONMENT"
    log_info "Services are running and ready for production traffic"
    log_info "URL: https://chitlaq.com"
}

# Error handling
trap 'log_error "Production deployment failed at line $LINENO"; disable_maintenance_mode; rollback; exit 1' ERR

# Parse arguments and run main function
parse_args "$@"
main
