-- ChitLaq M1 MVP - University Domains Seed Data
-- Comprehensive list of university email domains for validation
-- Generated by PROMPT 1.3 - Database Schema & Migrations

-- Insert university domains for email validation
INSERT INTO university_domains (domain, university_name, country_code, is_active, verification_required) VALUES

-- Turkish Universities
('metu.edu.tr', 'Middle East Technical University', 'TR', true, true),
('boun.edu.tr', 'Boğaziçi University', 'TR', true, true),
('itu.edu.tr', 'Istanbul Technical University', 'TR', true, true),
('ku.edu.tr', 'Koç University', 'TR', true, true),
('sabanciuniv.edu', 'Sabancı University', 'TR', true, true),
('bilkent.edu.tr', 'Bilkent University', 'TR', true, true),
('hacettepe.edu.tr', 'Hacettepe University', 'TR', true, true),
('ankara.edu.tr', 'Ankara University', 'TR', true, true),
('istanbul.edu.tr', 'Istanbul University', 'TR', true, true),
('yildiz.edu.tr', 'Yıldız Technical University', 'TR', true, true),
('gsu.edu.tr', 'Galatasaray University', 'TR', true, true),
('bahcesehir.edu.tr', 'Bahçeşehir University', 'TR', true, true),
('ozyegin.edu.tr', 'Özyeğin University', 'TR', true, true),
('isik.edu.tr', 'Işık University', 'TR', true, true),
('ege.edu.tr', 'Ege University', 'TR', true, true),
('deu.edu.tr', 'Dokuz Eylül University', 'TR', true, true),
('akdeniz.edu.tr', 'Akdeniz University', 'TR', true, true),
('erciyes.edu.tr', 'Erciyes University', 'TR', true, true),
('ktu.edu.tr', 'Karadeniz Technical University', 'TR', true, true),
('uludag.edu.tr', 'Uludağ University', 'TR', true, true),
('anadolu.edu.tr', 'Anadolu University', 'TR', true, true),
('gazi.edu.tr', 'Gazi University', 'TR', true, true),
('atilim.edu.tr', 'Atılım University', 'TR', true, true),
('cankaya.edu.tr', 'Çankaya University', 'TR', true, true),
('tobb.edu.tr', 'TOBB University of Economics and Technology', 'TR', true, true),

-- United States Universities
('mit.edu', 'Massachusetts Institute of Technology', 'US', true, true),
('stanford.edu', 'Stanford University', 'US', true, true),
('harvard.edu', 'Harvard University', 'US', true, true),
('berkeley.edu', 'University of California, Berkeley', 'US', true, true),
('cmu.edu', 'Carnegie Mellon University', 'US', true, true),
('caltech.edu', 'California Institute of Technology', 'US', true, true),
('princeton.edu', 'Princeton University', 'US', true, true),
('yale.edu', 'Yale University', 'US', true, true),
('columbia.edu', 'Columbia University', 'US', true, true),
('nyu.edu', 'New York University', 'US', true, true),
('upenn.edu', 'University of Pennsylvania', 'US', true, true),
('cornell.edu', 'Cornell University', 'US', true, true),
('uchicago.edu', 'University of Chicago', 'US', true, true),
('northwestern.edu', 'Northwestern University', 'US', true, true),
('duke.edu', 'Duke University', 'US', true, true),
('jhu.edu', 'Johns Hopkins University', 'US', true, true),
('brown.edu', 'Brown University', 'US', true, true),
('dartmouth.edu', 'Dartmouth College', 'US', true, true),
('rice.edu', 'Rice University', 'US', true, true),
('vanderbilt.edu', 'Vanderbilt University', 'US', true, true),
('emory.edu', 'Emory University', 'US', true, true),
('georgetown.edu', 'Georgetown University', 'US', true, true),
('gatech.edu', 'Georgia Institute of Technology', 'US', true, true),
('usc.edu', 'University of Southern California', 'US', true, true),
('ucla.edu', 'University of California, Los Angeles', 'US', true, true),
('ucsd.edu', 'University of California, San Diego', 'US', true, true),
('ucsb.edu', 'University of California, Santa Barbara', 'US', true, true),
('uci.edu', 'University of California, Irvine', 'US', true, true),
('ucdavis.edu', 'University of California, Davis', 'US', true, true),
('utexas.edu', 'University of Texas at Austin', 'US', true, true),
('umich.edu', 'University of Michigan', 'US', true, true),
('wisc.edu', 'University of Wisconsin-Madison', 'US', true, true),
('illinois.edu', 'University of Illinois at Urbana-Champaign', 'US', true, true),
('washington.edu', 'University of Washington', 'US', true, true),

-- United Kingdom Universities
('ox.ac.uk', 'University of Oxford', 'GB', true, true),
('cam.ac.uk', 'University of Cambridge', 'GB', true, true),
('imperial.ac.uk', 'Imperial College London', 'GB', true, true),
('ucl.ac.uk', 'University College London', 'GB', true, true),
('kcl.ac.uk', 'King\'s College London', 'GB', true, true),
('lse.ac.uk', 'London School of Economics', 'GB', true, true),
('ed.ac.uk', 'University of Edinburgh', 'GB', true, true),
('manchester.ac.uk', 'University of Manchester', 'GB', true, true),
('warwick.ac.uk', 'University of Warwick', 'GB', true, true),
('bristol.ac.uk', 'University of Bristol', 'GB', true, true),
('glasgow.ac.uk', 'University of Glasgow', 'GB', true, true),
('dur.ac.uk', 'Durham University', 'GB', true, true),
('st-andrews.ac.uk', 'University of St Andrews', 'GB', true, true),
('bath.ac.uk', 'University of Bath', 'GB', true, true),
('york.ac.uk', 'University of York', 'GB', true, true),
('exeter.ac.uk', 'University of Exeter', 'GB', true, true),
('lancaster.ac.uk', 'Lancaster University', 'GB', true, true),
('nottingham.ac.uk', 'University of Nottingham', 'GB', true, true),
('sheffield.ac.uk', 'University of Sheffield', 'GB', true, true),
('birmingham.ac.uk', 'University of Birmingham', 'GB', true, true),

-- Canadian Universities
('utoronto.ca', 'University of Toronto', 'CA', true, true),
('ubc.ca', 'University of British Columbia', 'CA', true, true),
('mcgill.ca', 'McGill University', 'CA', true, true),
('uwaterloo.ca', 'University of Waterloo', 'CA', true, true),
('queensu.ca', 'Queen\'s University', 'CA', true, true),
('mcmaster.ca', 'McMaster University', 'CA', true, true),
('ualberta.ca', 'University of Alberta', 'CA', true, true),
('uottawa.ca', 'University of Ottawa', 'CA', true, true),
('concordia.ca', 'Concordia University', 'CA', true, true),
('yorku.ca', 'York University', 'CA', true, true),

-- Australian Universities
('anu.edu.au', 'Australian National University', 'AU', true, true),
('sydney.edu.au', 'University of Sydney', 'AU', true, true),
('unsw.edu.au', 'University of New South Wales', 'AU', true, true),
('unimelb.edu.au', 'University of Melbourne', 'AU', true, true),
('monash.edu', 'Monash University', 'AU', true, true),
('uq.edu.au', 'University of Queensland', 'AU', true, true),
('adelaide.edu.au', 'University of Adelaide', 'AU', true, true),
('uwa.edu.au', 'University of Western Australia', 'AU', true, true),

-- German Universities
('tum.de', 'Technical University of Munich', 'DE', true, true),
('uni-heidelberg.de', 'Heidelberg University', 'DE', true, true),
('lmu.de', 'Ludwig Maximilian University of Munich', 'DE', true, true),
('kit.edu', 'Karlsruhe Institute of Technology', 'DE', true, true),
('hu-berlin.de', 'Humboldt University of Berlin', 'DE', true, true),
('fu-berlin.de', 'Free University of Berlin', 'DE', true, true),
('tu-berlin.de', 'Technical University of Berlin', 'DE', true, true),
('rwth-aachen.de', 'RWTH Aachen University', 'DE', true, true),
('uni-goettingen.de', 'University of Göttingen', 'DE', true, true),
('uni-freiburg.de', 'University of Freiburg', 'DE', true, true),

-- French Universities
('sorbonne-universite.fr', 'Sorbonne University', 'FR', true, true),
('ens.fr', 'École Normale Supérieure', 'FR', true, true),
('polytechnique.edu', 'École Polytechnique', 'FR', true, true),
('universite-paris-saclay.fr', 'University of Paris-Saclay', 'FR', true, true),
('univ-paris1.fr', 'Panthéon-Sorbonne University', 'FR', true, true),
('sciences-po.fr', 'Sciences Po', 'FR', true, true),

-- Japanese Universities
('u-tokyo.ac.jp', 'University of Tokyo', 'JP', true, true),
('kyoto-u.ac.jp', 'Kyoto University', 'JP', true, true),
('titech.ac.jp', 'Tokyo Institute of Technology', 'JP', true, true),
('osaka-u.ac.jp', 'Osaka University', 'JP', true, true),
('tohoku.ac.jp', 'Tohoku University', 'JP', true, true),
('nagoya-u.ac.jp', 'Nagoya University', 'JP', true, true),
('keio.ac.jp', 'Keio University', 'JP', true, true),
('waseda.jp', 'Waseda University', 'JP', true, true),

-- Chinese Universities
('pku.edu.cn', 'Peking University', 'CN', true, true),
('tsinghua.edu.cn', 'Tsinghua University', 'CN', true, true),
('sjtu.edu.cn', 'Shanghai Jiao Tong University', 'CN', true, true),
('zju.edu.cn', 'Zhejiang University', 'CN', true, true),
('fudan.edu.cn', 'Fudan University', 'CN', true, true),
('ust.hk', 'Hong Kong University of Science and Technology', 'HK', true, true),
('hku.hk', 'University of Hong Kong', 'HK', true, true),

-- Indian Universities
('iitb.ac.in', 'Indian Institute of Technology Bombay', 'IN', true, true),
('iitd.ac.in', 'Indian Institute of Technology Delhi', 'IN', true, true),
('iitk.ac.in', 'Indian Institute of Technology Kanpur', 'IN', true, true),
('iitm.ac.in', 'Indian Institute of Technology Madras', 'IN', true, true),
('iisc.ac.in', 'Indian Institute of Science', 'IN', true, true),
('du.ac.in', 'University of Delhi', 'IN', true, true),
('jnu.ac.in', 'Jawaharlal Nehru University', 'IN', true, true),

-- South African Universities
('uct.ac.za', 'University of Cape Town', 'ZA', true, true),
('wits.ac.za', 'University of the Witwatersrand', 'ZA', true, true),
('up.ac.za', 'University of Pretoria', 'ZA', true, true),
('sun.ac.za', 'Stellenbosch University', 'ZA', true, true),

-- Brazilian Universities
('usp.br', 'University of São Paulo', 'BR', true, true),
('unicamp.br', 'University of Campinas', 'BR', true, true),
('ufrj.br', 'Federal University of Rio de Janeiro', 'BR', true, true),
('ufmg.br', 'Federal University of Minas Gerais', 'BR', true, true),

-- Netherlands Universities
('uva.nl', 'University of Amsterdam', 'NL', true, true),
('tudelft.nl', 'Delft University of Technology', 'NL', true, true),
('uu.nl', 'Utrecht University', 'NL', true, true),
('eur.nl', 'Erasmus University Rotterdam', 'NL', true, true),

-- Swiss Universities
('ethz.ch', 'ETH Zurich', 'CH', true, true),
('epfl.ch', 'École Polytechnique Fédérale de Lausanne', 'CH', true, true),
('uzh.ch', 'University of Zurich', 'CH', true, true),
('unige.ch', 'University of Geneva', 'CH', true, true),

-- Swedish Universities
('kth.se', 'KTH Royal Institute of Technology', 'SE', true, true),
('ki.se', 'Karolinska Institute', 'SE', true, true),
('su.se', 'Stockholm University', 'SE', true, true),
('gu.se', 'University of Gothenburg', 'SE', true, true),

-- Italian Universities
('unimi.it', 'University of Milan', 'IT', true, true),
('polimi.it', 'Polytechnic University of Milan', 'IT', true, true),
('unibo.it', 'University of Bologna', 'IT', true, true),
('uniroma1.it', 'Sapienza University of Rome', 'IT', true, true),

-- Spanish Universities
('uam.es', 'Autonomous University of Madrid', 'ES', true, true),
('ub.edu', 'University of Barcelona', 'ES', true, true),
('upc.edu', 'Polytechnic University of Catalonia', 'ES', true, true),
('ucm.es', 'Complutense University of Madrid', 'ES', true, true),

-- Russian Universities
('msu.ru', 'Moscow State University', 'RU', true, true),
('spbu.ru', 'Saint Petersburg State University', 'RU', true, true),
('mipt.ru', 'Moscow Institute of Physics and Technology', 'RU', true, true),
('hse.ru', 'Higher School of Economics', 'RU', true, true),

-- South Korean Universities
('snu.ac.kr', 'Seoul National University', 'KR', true, true),
('kaist.ac.kr', 'Korea Advanced Institute of Science and Technology', 'KR', true, true),
('postech.ac.kr', 'Pohang University of Science and Technology', 'KR', true, true),
('yonsei.ac.kr', 'Yonsei University', 'KR', true, true),

-- Norwegian Universities
('uio.no', 'University of Oslo', 'NO', true, true),
('ntnu.no', 'Norwegian University of Science and Technology', 'NO', true, true),
('uib.no', 'University of Bergen', 'NO', true, true),

-- Danish Universities
('ku.dk', 'University of Copenhagen', 'DK', true, true),
('dtu.dk', 'Technical University of Denmark', 'DK', true, true),
('au.dk', 'Aarhus University', 'DK', true, true),

-- Finnish Universities
('helsinki.fi', 'University of Helsinki', 'FI', true, true),
('aalto.fi', 'Aalto University', 'FI', true, true),
('tuni.fi', 'Tampere University', 'FI', true, true),

-- Austrian Universities
('univie.ac.at', 'University of Vienna', 'AT', true, true),
('tuwien.ac.at', 'Vienna University of Technology', 'AT', true, true),

-- Belgian Universities
('kuleuven.be', 'KU Leuven', 'BE', true, true),
('ugent.be', 'Ghent University', 'BE', true, true),
('vub.be', 'Vrije Universiteit Brussel', 'BE', true, true),

-- New Zealand Universities
('auckland.ac.nz', 'University of Auckland', 'NZ', true, true),
('otago.ac.nz', 'University of Otago', 'NZ', true, true),

-- Singapore Universities
('nus.edu.sg', 'National University of Singapore', 'SG', true, true),
('ntu.edu.sg', 'Nanyang Technological University', 'SG', true, true),

-- Israeli Universities
('tau.ac.il', 'Tel Aviv University', 'IL', true, true),
('huji.ac.il', 'Hebrew University of Jerusalem', 'IL', true, true),
('technion.ac.il', 'Technion - Israel Institute of Technology', 'IL', true, true),

-- Mexican Universities
('unam.mx', 'National Autonomous University of Mexico', 'MX', true, true),
('itesm.mx', 'Tecnológico de Monterrey', 'MX', true, true),

-- Chilean Universities
('uc.cl', 'Pontifical Catholic University of Chile', 'CL', true, true),
('uchile.cl', 'University of Chile', 'CL', true, true),

-- Additional Turkish Universities and Colleges
('marmara.edu.tr', 'Marmara University', 'TR', true, true),
('selcuk.edu.tr', 'Selçuk University', 'TR', true, true),
('firat.edu.tr', 'Fırat University', 'TR', true, true),
('cumhuriyet.edu.tr', 'Cumhuriyet University', 'TR', true, true),
('dicle.edu.tr', 'Dicle University', 'TR', true, true),
('inonu.edu.tr', 'İnönü University', 'TR', true, true),
('sdu.edu.tr', 'Süleyman Demirel University', 'TR', true, true),
('pau.edu.tr', 'Pamukkale University', 'TR', true, true),
('comu.edu.tr', 'Çanakkale Onsekiz Mart University', 'TR', true, true),
('dpu.edu.tr', 'Dumlupınar University', 'TR', true, true),
('nku.edu.tr', 'Namık Kemal University', 'TR', true, true),
('trakya.edu.tr', 'Trakya University', 'TR', true, true),
('beun.edu.tr', 'Bülent Ecevit University', 'TR', true, true),
('ibu.edu.tr', 'Abant İzzet Baysal University', 'TR', true, true),
('ksu.edu.tr', 'Kahramanmaraş Sütçü İmam University', 'TR', true, true),

-- Community Colleges and Technical Schools (US)
('student.austincc.edu', 'Austin Community College', 'US', true, false),
('my.cccd.edu', 'Coast Community College District', 'US', true, false),
('student.howardcc.edu', 'Howard Community College', 'US', true, false);

-- Create indexes for fast lookup
CREATE INDEX CONCURRENTLY idx_university_domains_lookup ON university_domains(domain, is_active);
CREATE INDEX CONCURRENTLY idx_university_domains_country ON university_domains(country_code, is_active);

-- Update statistics
ANALYZE university_domains;

-- Add some sample system configuration for university validation
INSERT INTO system_config (config_key, config_value, description, is_public) VALUES
('university_verification_enabled', 'true', 'Enable university email verification', false),
('university_verification_strict', 'false', 'Require manual verification for all university emails', false),
('university_auto_verify_domains', 'edu,edu.tr,ac.uk,ac.in,edu.au,ac.za,edu.sg,ac.nz', 'Auto-verify domains that are definitely educational', false),
('university_verification_timeout_hours', '48', 'Hours to wait for university email verification', false),
('university_allow_staff_domains', 'true', 'Allow staff/faculty email domains', false),
('university_require_student_prefix', 'false', 'Require student-specific email prefixes', false);

COMMENT ON TABLE university_domains IS 'Approved university domains for student email validation with comprehensive global coverage';
