-- University Database Seed Data
-- Comprehensive list of universities with email validation patterns
-- Generated for ChitLaq M1 MVP University Email Validation System

-- Insert universities with their email domains and validation patterns
INSERT INTO universities (
    id, name, domain, country, type, status, prefixes, departments, faculties,
    academic_year_format, email_format, verification_required, max_students,
    current_students, established_year, website, contact_email, phone, address,
    city, state, postal_code, timezone, language, accreditation, partnerships,
    features, metadata, created_at, updated_at
) VALUES

-- United States Universities
(
    gen_random_uuid(),
    'Massachusetts Institute of Technology',
    'mit.edu',
    'US',
    'private',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "sci_*", "art_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Science", "Arts"]',
    '["School of Engineering", "School of Science", "Sloan School of Management", "School of Architecture"]',
    'YYYY',
    'firstname.lastname@mit.edu',
    true,
    12000,
    0,
    1861,
    'https://web.mit.edu',
    'admissions@mit.edu',
    '+1-617-253-1000',
    '77 Massachusetts Ave',
    'Cambridge',
    'MA',
    '02139',
    'America/New_York',
    'en',
    '["NEASC", "ABET"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Top-tier private research university", "tags": ["research", "engineering", "technology"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'Stanford University',
    'stanford.edu',
    'US',
    'private',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "edu_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law", "Education"]',
    '["School of Engineering", "School of Medicine", "Graduate School of Business", "Law School"]',
    'YYYY',
    'firstname.lastname@stanford.edu',
    true,
    17000,
    0,
    1885,
    'https://stanford.edu',
    'admission@stanford.edu',
    '+1-650-723-2300',
    '450 Serra Mall',
    'Stanford',
    'CA',
    '94305',
    'America/Los_Angeles',
    'en',
    '["WASC", "ABET"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading private research university", "tags": ["research", "technology", "innovation"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'Harvard University',
    'harvard.edu',
    'US',
    'private',
    'active',
    '["*_*", "faculty_*", "staff_*", "admin_*"]',
    '["All Departments"]',
    '["Faculty of Arts and Sciences", "Harvard Medical School", "Harvard Business School", "Harvard Law School"]',
    'YYYY',
    'firstname.lastname@harvard.edu',
    true,
    23000,
    0,
    1636,
    'https://harvard.edu',
    'admissions@harvard.edu',
    '+1-617-495-1000',
    'Massachusetts Hall',
    'Cambridge',
    'MA',
    '02138',
    'America/New_York',
    'en',
    '["NEASC"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": false, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Oldest university in the US", "tags": ["ivy-league", "research", "prestigious"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'University of California, Berkeley',
    'berkeley.edu',
    'US',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "edu_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law", "Education"]',
    '["College of Engineering", "School of Medicine", "Haas School of Business", "School of Law"]',
    'YYYY',
    'firstname.lastname@berkeley.edu',
    true,
    45000,
    0,
    1868,
    'https://berkeley.edu',
    'admissions@berkeley.edu',
    '+1-510-642-6000',
    '110 Sproul Hall',
    'Berkeley',
    'CA',
    '94720',
    'America/Los_Angeles',
    'en',
    '["WASC", "ABET"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Top public research university", "tags": ["public", "research", "engineering"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'Carnegie Mellon University',
    'cmu.edu',
    'US',
    'private',
    'active',
    '["cs_*", "eng_*", "bus_*", "art_*", "sci_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Business", "Arts", "Science"]',
    '["School of Computer Science", "College of Engineering", "Tepper School of Business", "College of Fine Arts"]',
    'YYYY',
    'firstname.lastname@cmu.edu',
    true,
    15000,
    0,
    1900,
    'https://cmu.edu',
    'admissions@cmu.edu',
    '+1-412-268-2000',
    '5000 Forbes Avenue',
    'Pittsburgh',
    'PA',
    '15213',
    'America/New_York',
    'en',
    '["MSCHE", "ABET"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading in computer science and technology", "tags": ["technology", "computer-science", "research"], "priority": 1}',
    NOW(),
    NOW()
),

-- United Kingdom Universities
(
    gen_random_uuid(),
    'University of Oxford',
    'ox.ac.uk',
    'GB',
    'public',
    'active',
    '["*_*", "faculty_*", "staff_*", "admin_*"]',
    '["All Departments"]',
    '["Humanities", "Mathematical, Physical and Life Sciences", "Medical Sciences", "Social Sciences"]',
    'YYYY',
    'firstname.lastname@ox.ac.uk',
    true,
    24000,
    0,
    1096,
    'https://ox.ac.uk',
    'admissions@ox.ac.uk',
    '+44-1865-270000',
    'Wellington Square',
    'Oxford',
    'Oxfordshire',
    'OX1 2JD',
    'Europe/London',
    'en',
    '["QAA"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": false, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Oldest university in the English-speaking world", "tags": ["ancient", "research", "prestigious"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'University of Cambridge',
    'cam.ac.uk',
    'GB',
    'public',
    'active',
    '["*_*", "faculty_*", "staff_*", "admin_*"]',
    '["All Departments"]',
    '["Arts and Humanities", "Biological Sciences", "Clinical Medicine", "Human, Social and Political Science"]',
    'YYYY',
    'firstname.lastname@cam.ac.uk',
    true,
    23000,
    0,
    1209,
    'https://cam.ac.uk',
    'admissions@cam.ac.uk',
    '+44-1223-337733',
    'The Old Schools',
    'Cambridge',
    'Cambridgeshire',
    'CB2 1TN',
    'Europe/London',
    'en',
    '["QAA"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": false, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Second-oldest university in the English-speaking world", "tags": ["ancient", "research", "prestigious"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'Imperial College London',
    'imperial.ac.uk',
    'GB',
    'public',
    'active',
    '["eng_*", "med_*", "sci_*", "bus_*", "faculty_*", "staff_*"]',
    '["Engineering", "Medicine", "Science", "Business"]',
    '["Faculty of Engineering", "Faculty of Medicine", "Faculty of Natural Sciences", "Imperial College Business School"]',
    'YYYY',
    'firstname.lastname@imperial.ac.uk',
    true,
    20000,
    0,
    1907,
    'https://imperial.ac.uk',
    'admissions@imperial.ac.uk',
    '+44-20-7589-5111',
    'South Kensington Campus',
    'London',
    'England',
    'SW7 2AZ',
    'Europe/London',
    'en',
    '["QAA"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading science and engineering university", "tags": ["science", "engineering", "research"], "priority": 1}',
    NOW(),
    NOW()
),

-- Canadian Universities
(
    gen_random_uuid(),
    'University of Toronto',
    'utoronto.ca',
    'CA',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "edu_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law", "Education"]',
    '["Faculty of Applied Science and Engineering", "Faculty of Medicine", "Rotman School of Management", "Faculty of Law"]',
    'YYYY',
    'firstname.lastname@utoronto.ca',
    true,
    97000,
    0,
    1827,
    'https://utoronto.ca',
    'admissions@utoronto.ca',
    '+1-416-978-2011',
    '27 King''s College Circle',
    'Toronto',
    'ON',
    'M5S 1A1',
    'America/Toronto',
    'en',
    '["AUCC"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Largest university in Canada", "tags": ["research", "comprehensive", "large"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'University of British Columbia',
    'ubc.ca',
    'CA',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "edu_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law", "Education"]',
    '["Faculty of Applied Science", "Faculty of Medicine", "Sauder School of Business", "Peter A. Allard School of Law"]',
    'YYYY',
    'firstname.lastname@ubc.ca',
    true,
    66000,
    0,
    1908,
    'https://ubc.ca',
    'admissions@ubc.ca',
    '+1-604-822-2211',
    '2329 West Mall',
    'Vancouver',
    'BC',
    'V6T 1Z4',
    'America/Vancouver',
    'en',
    '["AUCC"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading research university in Western Canada", "tags": ["research", "comprehensive", "west-coast"], "priority": 1}',
    NOW(),
    NOW()
),

-- Australian Universities
(
    gen_random_uuid(),
    'University of Melbourne',
    'unimelb.edu.au',
    'AU',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "edu_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law", "Education"]',
    '["Faculty of Engineering and Information Technology", "Faculty of Medicine", "Melbourne Business School", "Melbourne Law School"]',
    'YYYY',
    'firstname.lastname@unimelb.edu.au',
    true,
    50000,
    0,
    1853,
    'https://unimelb.edu.au',
    'admissions@unimelb.edu.au',
    '+61-3-9035-5511',
    'Parkville',
    'Melbourne',
    'VIC',
    '3010',
    'Australia/Melbourne',
    'en',
    '["TEQSA"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading research university in Australia", "tags": ["research", "comprehensive", "melbourne"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'University of Sydney',
    'sydney.edu.au',
    'AU',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "edu_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law", "Education"]',
    '["Faculty of Engineering", "Faculty of Medicine", "University of Sydney Business School", "Sydney Law School"]',
    'YYYY',
    'firstname.lastname@sydney.edu.au',
    true,
    73000,
    0,
    1850,
    'https://sydney.edu.au',
    'admissions@sydney.edu.au',
    '+61-2-9351-2222',
    'Camperdown',
    'Sydney',
    'NSW',
    '2006',
    'Australia/Sydney',
    'en',
    '["TEQSA"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Australia''s first university", "tags": ["research", "comprehensive", "sydney"], "priority": 1}',
    NOW(),
    NOW()
),

-- German Universities
(
    gen_random_uuid(),
    'Technical University of Munich',
    'tum.de',
    'DE',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "sci_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Science"]',
    '["Department of Computer Science", "Department of Engineering", "School of Medicine", "TUM School of Management"]',
    'YYYY',
    'firstname.lastname@tum.de',
    true,
    50000,
    0,
    1868,
    'https://tum.de',
    'admissions@tum.de',
    '+49-89-289-01',
    'Arcisstraße 21',
    'Munich',
    'Bavaria',
    '80333',
    'Europe/Berlin',
    'de',
    '["AACSB", "EQUIS"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading technical university in Germany", "tags": ["technical", "engineering", "research"], "priority": 1}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'Ludwig Maximilian University of Munich',
    'lmu.de',
    'DE',
    'public',
    'active',
    '["*_*", "faculty_*", "staff_*", "admin_*"]',
    '["All Departments"]',
    '["Faculty of Medicine", "Faculty of Law", "Faculty of Economics", "Faculty of Philosophy"]',
    'YYYY',
    'firstname.lastname@lmu.de',
    true,
    52000,
    0,
    1472,
    'https://lmu.de',
    'admissions@lmu.de',
    '+49-89-2180-0',
    'Geschwister-Scholl-Platz 1',
    'Munich',
    'Bavaria',
    '80539',
    'Europe/Berlin',
    'de',
    '["AACSB"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": false, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "One of Europe''s oldest universities", "tags": ["ancient", "comprehensive", "research"], "priority": 1}',
    NOW(),
    NOW()
),

-- French Universities
(
    gen_random_uuid(),
    'Sorbonne University',
    'sorbonne-universite.fr',
    'FR',
    'public',
    'active',
    '["*_*", "faculty_*", "staff_*", "admin_*"]',
    '["All Departments"]',
    '["Faculty of Arts and Humanities", "Faculty of Science and Engineering", "Faculty of Medicine"]',
    'YYYY',
    'firstname.lastname@sorbonne-universite.fr',
    true,
    55000,
    0,
    1257,
    'https://sorbonne-universite.fr',
    'admissions@sorbonne-universite.fr',
    '+33-1-44-27-44-27',
    '21 rue de l''École de médecine',
    'Paris',
    'Île-de-France',
    '75006',
    'Europe/Paris',
    'fr',
    '["AERES"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": false, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "One of the oldest universities in the world", "tags": ["ancient", "comprehensive", "paris"], "priority": 1}',
    NOW(),
    NOW()
),

-- Japanese Universities
(
    gen_random_uuid(),
    'University of Tokyo',
    'u-tokyo.ac.jp',
    'JP',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law"]',
    '["Graduate School of Information Science and Technology", "Graduate School of Engineering", "Graduate School of Medicine"]',
    'YYYY',
    'firstname.lastname@u-tokyo.ac.jp',
    true,
    28000,
    0,
    1877,
    'https://u-tokyo.ac.jp',
    'admissions@u-tokyo.ac.jp',
    '+81-3-3812-2111',
    '7-3-1 Hongo',
    'Tokyo',
    'Tokyo',
    '113-8654',
    'Asia/Tokyo',
    'ja',
    '["MEXT"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Japan''s leading research university", "tags": ["research", "comprehensive", "tokyo"], "priority": 1}',
    NOW(),
    NOW()
),

-- Chinese Universities
(
    gen_random_uuid(),
    'Tsinghua University',
    'tsinghua.edu.cn',
    'CN',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law"]',
    '["School of Computer Science", "School of Engineering", "School of Medicine", "School of Economics and Management"]',
    'YYYY',
    'firstname.lastname@tsinghua.edu.cn',
    true,
    46000,
    0,
    1911,
    'https://tsinghua.edu.cn',
    'admissions@tsinghua.edu.cn',
    '+86-10-6278-3000',
    'Tsinghua University',
    'Beijing',
    'Beijing',
    '100084',
    'Asia/Shanghai',
    'zh',
    '["MOE"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading research university in China", "tags": ["research", "engineering", "beijing"], "priority": 1}',
    NOW(),
    NOW()
),

-- Indian Universities
(
    gen_random_uuid(),
    'Indian Institute of Technology Bombay',
    'iitb.ac.in',
    'IN',
    'public',
    'active',
    '["cs_*", "eng_*", "sci_*", "bus_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Science", "Business"]',
    '["Department of Computer Science and Engineering", "Department of Electrical Engineering", "Department of Mechanical Engineering"]',
    'YYYY',
    'firstname.lastname@iitb.ac.in',
    true,
    12000,
    0,
    1958,
    'https://iitb.ac.in',
    'admissions@iitb.ac.in',
    '+91-22-2572-2545',
    'Powai',
    'Mumbai',
    'Maharashtra',
    '400076',
    'Asia/Kolkata',
    'en',
    '["AICTE"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Premier engineering institute in India", "tags": ["engineering", "technology", "mumbai"], "priority": 1}',
    NOW(),
    NOW()
),

-- Brazilian Universities
(
    gen_random_uuid(),
    'University of São Paulo',
    'usp.br',
    'BR',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law"]',
    '["Polytechnic School", "School of Medicine", "School of Economics", "School of Law"]',
    'YYYY',
    'firstname.lastname@usp.br',
    true,
    95000,
    0,
    1934,
    'https://usp.br',
    'admissions@usp.br',
    '+55-11-3091-4000',
    'Rua da Reitoria',
    'São Paulo',
    'SP',
    '05508-220',
    'America/Sao_Paulo',
    'pt',
    '["CAPES"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Largest university in Brazil", "tags": ["research", "comprehensive", "sao-paulo"], "priority": 1}',
    NOW(),
    NOW()
),

-- South African Universities
(
    gen_random_uuid(),
    'University of Cape Town',
    'uct.ac.za',
    'ZA',
    'public',
    'active',
    '["cs_*", "eng_*", "med_*", "bus_*", "law_*", "faculty_*", "staff_*"]',
    '["Computer Science", "Engineering", "Medicine", "Business", "Law"]',
    '["Faculty of Engineering", "Faculty of Health Sciences", "Faculty of Commerce", "Faculty of Law"]',
    'YYYY',
    'firstname.lastname@uct.ac.za',
    true,
    29000,
    0,
    1829,
    'https://uct.ac.za',
    'admissions@uct.ac.za',
    '+27-21-650-9111',
    'Private Bag X3',
    'Cape Town',
    'Western Cape',
    '7701',
    'Africa/Johannesburg',
    'en',
    '["CHE"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": true, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading research university in South Africa", "tags": ["research", "comprehensive", "cape-town"], "priority": 1}',
    NOW(),
    NOW()
);

-- Insert additional universities for comprehensive coverage
-- Community Colleges (US)
INSERT INTO universities (
    id, name, domain, country, type, status, prefixes, departments, faculties,
    academic_year_format, email_format, verification_required, max_students,
    current_students, established_year, website, contact_email, phone, address,
    city, state, postal_code, timezone, language, accreditation, partnerships,
    features, metadata, created_at, updated_at
) VALUES

(
    gen_random_uuid(),
    'Santa Monica College',
    'smc.edu',
    'US',
    'community',
    'active',
    '["*_*", "faculty_*", "staff_*"]',
    '["All Departments"]',
    '["Academic Affairs", "Student Services", "Administrative Services"]',
    'YYYY',
    'firstname.lastname@smc.edu',
    true,
    30000,
    0,
    1929,
    'https://smc.edu',
    'admissions@smc.edu',
    '+1-310-434-4000',
    '1900 Pico Boulevard',
    'Santa Monica',
    'CA',
    '90405',
    'America/Los_Angeles',
    'en',
    '["ACCJC"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": false, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Leading community college in California", "tags": ["community-college", "transfer", "california"], "priority": 2}',
    NOW(),
    NOW()
),

(
    gen_random_uuid(),
    'Miami Dade College',
    'mdc.edu',
    'US',
    'community',
    'active',
    '["*_*", "faculty_*", "staff_*"]',
    '["All Departments"]',
    '["Academic Affairs", "Student Services", "Administrative Services"]',
    'YYYY',
    'firstname.lastname@mdc.edu',
    true,
    165000,
    0,
    1960,
    'https://mdc.edu',
    'admissions@mdc.edu',
    '+1-305-237-8888',
    '300 NE 2nd Avenue',
    'Miami',
    'FL',
    '33132',
    'America/New_York',
    'en',
    '["SACSCOC"]',
    '[]',
    '{"allowFaculty": true, "allowStaff": true, "allowAlumni": false, "requirePrefix": false, "requireAcademicYear": false, "allowMultipleEmails": false, "enableGeographicValidation": true, "enableFraudDetection": true}',
    '{"lastVerified": "2024-01-01T00:00:00Z", "verificationSource": "official", "notes": "Largest community college in the US", "tags": ["community-college", "large", "miami"], "priority": 2}',
    NOW(),
    NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_universities_domain ON universities(domain);
CREATE INDEX IF NOT EXISTS idx_universities_country ON universities(country);
CREATE INDEX IF NOT EXISTS idx_universities_type ON universities(type);
CREATE INDEX IF NOT EXISTS idx_universities_status ON universities(status);
CREATE INDEX IF NOT EXISTS idx_universities_name ON universities(name);

-- Create full-text search index
CREATE INDEX IF NOT EXISTS idx_universities_search ON universities USING gin(to_tsvector('english', name || ' ' || domain));

-- Update statistics
ANALYZE universities;
